name: packages

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2.3.0
      - name: Install Dependencies in Another Package
        working-directory: another_package
        run: flutter packages get

      - name: Flutter Package
        - name: Install deps
          working-directory: flutter_package
          run: flutter packages get

      - name: Install Dependencies in Package.
        working-directory: package
        run: flutter packages get

      - name: Format Another Package
        working-directory: another_package
        run: flutter format --set-exit-if-changed lib test

      - name: Format Flutter Package
        working-directory: flutter_package
        run: flutter format --set-exit-if-changed lib test

      - name: Format Package
        working-directory: package
        run: flutter format --set-exit-if-changed lib test

      - name: Analyze Another Package
        working-directory: another_package
        run: flutter analyze lib test

      - name: Analyze Flutter Package.
        working-directory: flutter_package
        run: flutter analyze lib test

      - name: Analyze Package
        working-directory: package
        run: flutter analyze lib test

      # - name: Run tests
      #   run: flutter test

      #   working-directory: flutter_package
      # - name: Install Dependencies
      #   run: flutter packages get
      # - name: Format
      #   run: flutter format --set-exit-if-changed lib test
      # - name: Analyze
      #   run: flutter analyze lib test
      # - name: Run tests
      #   run: flutter test --no-pub --coverage

      #   working-directory: package
      # - name: Install Dependencies
      #   run: flutter packages get
      # - name: Format
      #   run: flutter format --set-exit-if-changed lib test
      # - name: Analyze
      #   run: flutter analyze lib test
      # - name: Run tests
      #   run: flutter test --no-pub --coverage
