name: packages

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.0
      - name: Install Dependencies
        working-directory: another_package
        run: flutter pub get
        working-directory: flutter_package
        run: flutter pub get
        working-directory: package
        run: flutter pub get

      - name: Format
        working-directory: another_package
        run: flutter format --set-exit-if-changed lib test
        working-directory: flutter_package
        run: flutter format --set-exit-if-changed lib test
        working-directory: package
        run: flutter format --set-exit-if-changed lib test

      - name: Analyze
        working-directory: another_package
        run: flutter analyze lib test
        working-directory: flutter_package
        run: flutter analyze lib test
        working-directory: package
        run: flutter analyze lib test

      # - name: Run tests
      #   run: flutter test

      #   working-directory: flutter_package
      # - name: Install Dependencies
      #   run: flutter packages get
      # - name: Format
      #   run: flutter format --set-exit-if-changed lib test
      # - name: Analyze
      #   run: flutter analyze lib test
      # - name: Run tests
      #   run: flutter test --no-pub --coverage

      #   working-directory: package
      # - name: Install Dependencies
      #   run: flutter packages get
      # - name: Format
      #   run: flutter format --set-exit-if-changed lib test
      # - name: Analyze
      #   run: flutter analyze lib test
      # - name: Run tests
      #   run: flutter test --no-pub --coverage
